import { data, Form, useActionData, useNavigation } from "react-router";
import { actionError, formString, load, requirePermission } from "~/.server/guards";
import { createClient, listAdminClients, updateClient } from "~/.server/services/admin-crud";
import { Button, ErrorSummary, TextField } from "~/components/ui/forms";
import { formatDateTime, PageHeading, Panel } from "~/components/workspace/WorkspaceShell";
import type { Route } from "./+types/clients";

export async function loader({context,request}:Route.LoaderArgs){const actor=await requirePermission(context,request,"clients.view");return{items:await listAdminClients(load(context).server,actor)}}
export async function action({context,request}:Route.ActionArgs){const actor=await requirePermission(context,request,"clients.manage");const form=await request.formData();try{const intent=formString(form,"intent");if(intent==="create"){await createClient(load(context).server,actor,Object.fromEntries(form));return data({ok:true,message:"Client created."})}await updateClient(load(context).server,actor,formString(form,"id"),Object.fromEntries(form));return data({ok:true,message:"Client saved."})}catch(e){return actionError(e)}}
export default function Clients({loaderData}:Route.ComponentProps){const result=useActionData<typeof action>();const busy=useNavigation().state==="submitting";return <><PageHeading eyebrow="Admin" title="Clients" description="Client organisations and their active engagements."/><Panel title="New client"><Form method="post" className="v-form v-form--tight"><input type="hidden" name="intent" value="create"/><TextField name="name" label="Name" required/><TextField name="slug" label="Slug" required/><TextField name="websiteUrl" label="Website URL"/><Button busy={busy} size="s">Create client</Button></Form></Panel>{result?.ok?<p className="v-notice v-notice--success">{result.message}</p>:null}{result&&!result.ok?<ErrorSummary message={result.message} fields={result.fields}/>:null}<Panel title="Client organisations" flush>{loaderData.items.length===0?<div className="v-panel__body"><p className="v-body">No client organisations yet.</p></div>:<div className="v-tablewrap"><table className="v-table v-table--stack"><caption className="v-sr">Client organisations</caption><thead><tr><th>Name</th><th>Status</th><th>Engagements</th><th>Created</th></tr></thead><tbody>{loaderData.items.map(item=><tr key={item.id}><td><strong>{item.name}</strong><div className="v-body-s">{item.slug}</div></td><td>{item.status}</td><td className="v-data">{item.engagements}</td><td className="v-data">{formatDateTime(item.createdAt)}</td></tr>)}</tbody></table></div>}</Panel></>}