import { data, Form, useActionData, useNavigation } from "react-router";
import { actionError, formString, load, requirePermission } from "~/.server/guards";
import { createEngagement, listAdminEngagements, updateEngagement } from "~/.server/services/admin-crud";
import { Button, ErrorSummary, TextField } from "~/components/ui/forms";
import { PageHeading, Panel } from "~/components/workspace/WorkspaceShell";
import type { Route } from "./+types/engagements";

export async function loader({context,request}:Route.LoaderArgs){const actor=await requirePermission(context,request,"engagements.view");return{items:await listAdminEngagements(load(context).server,actor)}}
export async function action({context,request}:Route.ActionArgs){const form=await request.formData(),intent=formString(form,"intent"),server=load(context).server;try{const actor=await requirePermission(context,request,"engagements.manage");if(intent==="create"){await createEngagement(server,actor,Object.fromEntries(form));return data({ok:true,message:"Engagement created."})}if(intent==="update"){await updateEngagement(server,actor,formString(form,"id"),Object.fromEntries(form));return data({ok:true,message:"Engagement saved."})}return data({ok:false,message:"Unknown action.",fields:{}},{status:400})}catch(e){return actionError(e)}}
export default function Engagements({loaderData}:Route.ComponentProps){const result=useActionData<typeof action>();const busy=useNavigation().state==="submitting";return <><PageHeading eyebrow="Admin" title="Engagements" description="Run client work from planning through delivery."/><Panel title="New engagement"><Form method="post" className="v-form v-form--tight"><input type="hidden" name="intent" value="create"/><TextField name="orgId" label="Client organisation ID" required/><TextField name="name" label="Name" required/><TextField name="summary" label="Summary"/><TextField name="startDate" label="Start date" type="date"/><TextField name="targetDate" label="Target date" type="date"/><label className="v-label">Status<select className="v-select" name="status" defaultValue="planning"><option value="planning">Planning</option><option value="in_progress">In progress</option><option value="review">Review</option><option value="delivered">Delivered</option><option value="on_hold">On hold</option><option value="closed">Closed</option></select></label><Button busy={busy} size="s">Create engagement</Button></Form></Panel>{result?.ok?<p className="v-notice v-notice--success">{result.message}</p>:null}{result&&!result.ok?<ErrorSummary message={result.message} fields={result.fields}/>:null}<Panel title="Engagements" flush><div className="v-tablewrap"><table className="v-table v-table--stack"><caption className="v-sr">Engagements</caption><thead><tr><th>Name</th><th>Client</th><th>Status</th><th>Dates</th></tr></thead><tbody>{loaderData.items.map(e=><tr key={e.id}><td><strong>{e.name}</strong><div className="v-body-s">{e.id}</div></td><td>{e.orgName}</td><td><Form method="post" className="v-inline-form"><input type="hidden" name="intent" value="update"/><input type="hidden" name="id" value={e.id}/><input type="hidden" name="name" value={e.name}/><input type="hidden" name="summary" value={e.summary ?? ""}/><input type="hidden" name="startDate" value={e.startDate ?? ""}/><input type="hidden" name="targetDate" value={e.targetDate ?? ""}/><select className="v-select" name="status" defaultValue={e.status}><option value="planning">Planning</option><option value="in_progress">In progress</option><option value="review">Review</option><option value="delivered">Delivered</option><option value="on_hold">On hold</option><option value="closed">Closed</option></select><button className="v-btn v-btn--secondary v-btn--s">Save</button></Form></td><td>{e.startDate??"—"} → {e.targetDate??"—"}</td></tr>)}</tbody></table></div></Panel></>}