import { data, Form, useActionData, useNavigation } from "react-router";
import { actionError, formString, load, requirePermission } from "~/.server/guards";
import { createService, listAdminServices, publishService, updateService } from "~/.server/services/admin-crud";
import { Button, ErrorSummary, TextField } from "~/components/ui/forms";
import { formatDateTime, PageHeading, Panel } from "~/components/workspace/WorkspaceShell";
import type { Route } from "./+types/services";

export async function loader({context,request}:Route.LoaderArgs){const actor=await requirePermission(context,request,"services.view");return{items:await listAdminServices(load(context).server,actor)}}
export async function action({context,request}:Route.ActionArgs){const form=await request.formData(),intent=formString(form,"intent"),server=load(context).server;try{const actor=await requirePermission(context,request,intent==="publish"?"services.publish":"services.edit");if(intent==="create"){await createService(server,actor,Object.fromEntries(form));return data({ok:true,message:"Service created."})}if(intent==="update"){await updateService(server,actor,formString(form,"id"),Object.fromEntries(form));return data({ok:true,message:"Service saved."})}if(intent==="publish"){await publishService(server,actor,formString(form,"id"));return data({ok:true,message:"Service published."})}return data({ok:false,message:"Unknown action.",fields:{}},{status:400})}catch(e){return actionError(e)}}
export default function Services({loaderData}:Route.ComponentProps){const result=useActionData<typeof action>();const busy=useNavigation().state==="submitting";return <><PageHeading eyebrow="Admin" title="Services" description="Create, edit and publish VORA capabilities."/><Panel title="New service"><Form method="post" className="v-form v-form--tight"><input type="hidden" name="intent" value="create"/><TextField name="title" label="Name" required/><TextField name="slug" label="Slug" required/><TextField name="summary" label="Summary"/><TextField name="partnerId" label="Partner ID (required for partner/joint)"/><label className="v-label">Delivery model<select className="v-select" name="deliveryModel" defaultValue="vora"><option value="vora">VORA</option><option value="partner">Partner</option><option value="joint">Joint</option></select></label><TextField name="body" label="Content blocks JSON" defaultValue="[]"/><Button busy={busy} size="s">Create service</Button></Form></Panel>{result?.ok?<p className="v-notice v-notice--success">{result.message}</p>:null}{result&&!result.ok?<ErrorSummary message={result.message} fields={result.fields}/>:null}<Panel title="Services" flush>{loaderData.items.length===0?<div className="v-panel__body"><p className="v-body">No services yet.</p></div>:<div className="v-tablewrap"><table className="v-table v-table--stack"><caption className="v-sr">Services</caption><thead><tr><th>Service</th><th>Delivery</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{loaderData.items.map(s=><tr key={s.id}><td><strong>{s.name}</strong><div className="v-body-s">{s.slug}</div></td><td>{s.deliveryModel}</td><td>{s.status}{s.hasUnpublishedChanges?" · draft":""}</td><td className="v-data">{formatDateTime(s.updatedAt)}</td><td><div className="v-actions"><a className="v-btn v-btn--secondary v-btn--s" href={`/admin/services/${s.id}`}>Edit</a><Form method="post"><input type="hidden" name="intent" value="publish"/><input type="hidden" name="id" value={s.id}/><button className="v-btn v-btn--secondary v-btn--s" disabled={!s.hasUnpublishedChanges}>Publish</button></Form></td></tr>)}</tbody></table></div>}</Panel></>}