import { data, Form, useActionData, useNavigation } from "react-router";
import { eq } from "drizzle-orm";
import { actionError, load, requirePermission } from "~/.server/guards";
import { updateService } from "~/.server/services/admin-crud";
import { schema } from "~/.server/db/client";
import { Button, ErrorSummary, TextField } from "~/components/ui/forms";
import { PageHeading, Panel } from "~/components/workspace/WorkspaceShell";
import type { Route } from "./+types/service";
export async function loader({context,request,params}:Route.LoaderArgs){await requirePermission(context,request,"services.view");const row=await load(context).server.db.select().from(schema.services).where(eq(schema.services.id,params.id)).get();if(!row)throw new Response("Not found",{status:404});return{row}}
export async function action({context,request,params}:Route.ActionArgs){const actor=await requirePermission(context,request,"services.edit");try{await updateService(load(context).server,actor,params.id,Object.fromEntries(await request.formData()));return data({ok:true,message:"Service saved."})}catch(e){return actionError(e)}}
export default function Service({loaderData}:Route.ComponentProps){const r=useActionData<typeof action>();const busy=useNavigation().state==="submitting";const s=loaderData.row;return <><PageHeading eyebrow="Admin / Services" title={s.name}/>{r?.ok?<p className="v-notice v-notice--success">{r.message}</p>:null}{r&&!r.ok?<ErrorSummary message={r.message} fields={r.fields}/>:null}<Panel title="Working copy"><Form method="post" className="v-form v-form--tight"><TextField name="title" label="Name" defaultValue={s.name} required/><TextField name="slug" label="Slug" defaultValue={s.slug} required/><TextField name="summary" label="Summary" defaultValue={s.summary ?? ""}/><TextField name="partnerId" label="Partner ID" defaultValue={s.partnerId ?? ""}/><label className="v-label">Delivery model<select className="v-select" name="deliveryModel" defaultValue={s.deliveryModel}><option value="vora">VORA</option><option value="partner">Partner</option><option value="joint">Joint</option></select></label><TextField name="body" label="Content blocks JSON" defaultValue={JSON.stringify(s.body)}/><Button busy={busy} size="s">Save draft</Button></Form></Panel></>}
